spring:
  messages:
    basename: errors
  profiles:
    include: sub
    group:
      set1: set1
      set2: set2
  datasource:
    url: jdbc:mariadb://localhost:3306/skillExchange?serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root1234
#  mvc:
#    static-path-pattern: /static/**


  #  sql:
#    init:
#      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          time_zone: Asia/Seoul
#    defer-datasource-initialization: true

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
    org.apache.coyote.http11: debug


server:
  port: 80