# 에러 메세지 (errors.properties) 위치
spring:
  messages:
    basename: errors
  profiles:
    include: sub
    group:
      set1: set1
      set2: set2
#  datasource:
#    url: jdbc:mariadb://localhost:3306/skillExchange
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: root1234


#  sql:
#    init:
#      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
#    defer-datasource-initialization: true

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
    org.apache.coyote.http11: debug

#
#server:
#  port: 80